## Matrix Creation

In [ ]:
1 + 2

3

In [ ]:
import numpy

We use **numpy** lib for matrixes manipulations


Refer to the documentation of the library

https://numpy.org/doc/stable/search.html?q=asarray&check_keywords=yes&area=default

Use **numpy.random.rand(shape)** to create randomly initialized matrix

In [ ]:
w_1 = numpy.random.rand(3, 3)
print('Shape: ', w_1.shape)
print(w_1)

Shape:  (3, 3)
[[0.13400891 0.40076782 0.62634514]
 [0.84853228 0.86055006 0.41897943]
 [0.6857977  0.83809908 0.76477515]]


## Create Integer Matrix with shape 3x3, where maximum value is 20

In [ ]:
w_1 = numpy.random.randint(20, size=(3, 3))
print('Shape: ', w_1.shape)
print(w_1)

Shape:  (3, 3)
[[14 18 15]
 [19  5  6]
 [ 3 14 16]]


In [ ]:
w_2 = numpy.random.randint(10, size=(3, 1))
print('Shape: ', w_2.shape)
print(w_2)

Shape:  (3, 1)
[[1]
 [6]
 [6]]


## Matrix Transpose 

**numpy.asarray** - convert list to numpy array / matrix

In [ ]:
w_1 = numpy.asarray([[1],[2],[3]])
print('Shape: ', w_1.shape)
print(w_1)

Shape:  (3, 1)
[[1]
 [2]
 [3]]


**.T** computes the transpose of matrix

In [ ]:
w_1 = w_1.T
print('Shape: ', w_1.shape)
print(w_1)

Shape:  (1, 3)
[[1 2 3]]


## Matrix Multiplication

Use **numpy.dot(w1, w2)** function to compute 

dot product / matrix multiplication for matrixes w1 and w2

---



In [ ]:
w_1 = numpy.asarray([[1, 2, 3]])
print('Shape: ', w_1.shape)
print(w_1)

print('----')
w_2 = numpy.asarray([[1, 1, 1], 
                     [0, 1, 1], 
                     [0, 0, 1]])
print('Shape: ', w_2.shape)
print(w_2)

Shape:  (1, 3)
[[1 2 3]]
----
Shape:  (3, 3)
[[1 1 1]
 [0 1 1]
 [0 0 1]]


In [ ]:
w_3 = numpy.dot(w_1, w_2)
print('Shape: ', w_3.shape)
print(w_3)

Shape:  (1, 3)
[[1 3 6]]


In [ ]:
numpy.dot(w_2, w_1)

ValueError: ignored

Simple multiplication sign (*) will make element-wise multiplication

In [ ]:
w_4 = w_3 * 2
print('Shape: ', w_4.shape)
print(w_4)

Shape:  (1, 3)
[[ 2  6 12]]


In [ ]:
1 - (-1)

2

# 3 Layer Example

In [ ]:
import numpy

In [ ]:
I = numpy.asarray([[0.9, 0.1, 0.8]]).T
print(I.shape)
print(I)

(3, 1)
[[0.9]
 [0.1]
 [0.8]]


In [ ]:
W_input_hidden = numpy.asarray(
    [[0.9, 0.3, 0.4], 
     [0.2, 0.8, 0.2], 
     [0.1, 0.5, 0.6]])
print(W_input_hidden.shape)
print(W_input_hidden)
print('-------')
W_hidden_output = numpy.asarray(
    [[0.3, 0.7, 0.5], 
     [0.6, 0.5, 0.2], 
     [0.8, 0.1, 0.9]])
print(W_hidden_output.shape)
print(W_hidden_output)

(3, 3)
[[0.9 0.3 0.4]
 [0.2 0.8 0.2]
 [0.1 0.5 0.6]]
-------
(3, 3)
[[0.3 0.7 0.5]
 [0.6 0.5 0.2]
 [0.8 0.1 0.9]]


In [ ]:
X_hidden = numpy.dot(W_input_hidden, I)
print(X_hidden.shape)
print(X_hidden)

(3, 1)
[[1.16]
 [0.42]
 [0.62]]


In [ ]:
import scipy.special
sigmoid_function = lambda x: scipy.special.expit(x)

In [ ]:
O_hidden = sigmoid_function(X_hidden)
print(O_hidden.shape)
print(O_hidden)

(3, 1)
[[0.76133271]
 [0.60348325]
 [0.65021855]]


In [ ]:
X_output = numpy.dot(W_hidden_output, O_hidden)
print(X_output.shape)
print(X_output)

(3, 1)
[[0.97594736]
 [0.88858496]
 [1.25461119]]


In [ ]:
O_output = sigmoid_function(X_output)
print(O_output.shape)
print(O_output)

(3, 1)
[[0.72630335]
 [0.70859807]
 [0.77809706]]
