# Forward Propagation

In [ ]:
import numpy

In [ ]:
I = numpy.asarray([[0.9, 0.1, 0.8]]).T
print(I.shape)
print(I)

(3, 1)
[[0.9]
 [0.1]
 [0.8]]


In [ ]:
W_input_hidden = numpy.asarray(
    [[0.9, 0.3, 0.4], 
     [0.2, 0.8, 0.2], 
     [0.1, 0.5, 0.6]])
print(W_input_hidden.shape)
print(W_input_hidden)

(3, 3)
[[0.9 0.3 0.4]
 [0.2 0.8 0.2]
 [0.1 0.5 0.6]]


In [ ]:
W_hidden_output = numpy.asarray(
    [[0.3, 0.7, 0.5], 
     [0.6, 0.5, 0.2], 
     [0.8, 0.1, 0.9]])
print(W_hidden_output.shape)
print(W_hidden_output)

(3, 3)
[[0.3 0.7 0.5]
 [0.6 0.5 0.2]
 [0.8 0.1 0.9]]


In [ ]:
X_hidden = numpy.dot(W_input_hidden, I)
print(X_hidden.shape)
print(X_hidden)

(3, 1)
[[1.16]
 [0.42]
 [0.62]]


In [ ]:
import scipy.special
sigmoid_function = lambda x: scipy.special.expit(x)

In [ ]:
O_hidden = sigmoid_function(X_hidden)
print(O_hidden.shape)
print(O_hidden)

(3, 1)
[[0.76133271]
 [0.60348325]
 [0.65021855]]


In [ ]:
X_output = numpy.dot(W_hidden_output, O_hidden)
print(X_output.shape)
print(X_output)

(3, 1)
[[0.97594736]
 [0.88858496]
 [1.25461119]]


In [ ]:
O_output = sigmoid_function(X_output)
print(O_output.shape)
print(O_output)

(3, 1)
[[0.72630335]
 [0.70859807]
 [0.77809706]]


# Backward Propagation

## Old Weights

In [ ]:
print(W_input_hidden.shape)
print(W_input_hidden)
print('-------')
print(W_hidden_output.shape)
print(W_hidden_output)

(3, 3)
[[0.9 0.3 0.4]
 [0.2 0.8 0.2]
 [0.1 0.5 0.6]]
-------
(3, 3)
[[0.3 0.7 0.5]
 [0.6 0.5 0.2]
 [0.8 0.1 0.9]]


In [ ]:
target = numpy.asarray([[0.6, 0.8, 0.5]]).T
print('--Sample Target--')
print(target.shape)
print(target)

--Sample Target--
(3, 1)
[[0.6]
 [0.8]
 [0.5]]


In [ ]:
output_error = (target - O_output)
hidden_error = numpy.dot(W_hidden_output.T, output_error)

W_hidden_output = W_hidden_output - (-0.01 * numpy.dot(output_error * O_output * (1 - O_output), O_hidden.T))
W_input_hidden = W_input_hidden - (-0.01 * numpy.dot(hidden_error * O_hidden * (1 - O_hidden), I.T))

In [ ]:
print(W_input_hidden.shape)
print(W_input_hidden)
print('-------')
print(W_hidden_output.shape)
print(W_hidden_output)

(3, 3)
[[0.89966389 0.29996265 0.39970124]
 [0.19984812 0.79998312 0.199865  ]
 [0.09939584 0.49993287 0.59946297]]
-------
(3, 3)
[[0.29980885 0.69984848 0.49983675]
 [0.60014369 0.5001139  0.20012272]
 [0.79963443 0.09971023 0.89968779]]


In [ ]:
# Sample Training and Testing

# Sample Training and Testing

In [ ]:
n_of_epochs = 800

I = numpy.asarray([[0.9, 0.1, 0.8]]).T
target = numpy.asarray([[0.6, 0.8, 0.5]]).T

W_input_hidden = numpy.asarray(
    [[0.9, 0.3, 0.4], 
     [0.2, 0.8, 0.2], 
     [0.1, 0.5, 0.6]])
W_hidden_output = numpy.asarray(
    [[0.3, 0.7, 0.5], 
     [0.6, 0.5, 0.2], 
     [0.8, 0.1, 0.9]])

In [ ]:
print('Weight Matrixes')
print(W_input_hidden.shape)
print(W_input_hidden)
print('-------')
print(W_hidden_output.shape)
print(W_hidden_output)

print('\nTarget:\n', target, '\n')


# Forward Pass
X_hidden = numpy.dot(W_input_hidden, I)
O_hidden = sigmoid_function(X_hidden)
X_output = numpy.dot(W_hidden_output, O_hidden)
O_output = sigmoid_function(X_output)

print('Output Before Training:\n', O_output)

Weight Matrixes
(3, 3)
[[0.9 0.3 0.4]
 [0.2 0.8 0.2]
 [0.1 0.5 0.6]]
-------
(3, 3)
[[0.3 0.7 0.5]
 [0.6 0.5 0.2]
 [0.8 0.1 0.9]]

Target:
 [[0.6]
 [0.8]
 [0.5]] 

Output Before Training:
 [[0.72630335]
 [0.70859807]
 [0.77809706]]


In [ ]:
for epoch in range(n_of_epochs):
  # Forward Pass
  X_hidden = numpy.dot(W_input_hidden, I)
  O_hidden = sigmoid_function(X_hidden)
  X_output = numpy.dot(W_hidden_output, O_hidden)
  O_output = sigmoid_function(X_output)


  # Backward Pass
  output_error = (target - O_output)
  hidden_error = numpy.dot(W_hidden_output.T, output_error)
  W_hidden_output = W_hidden_output - (-0.1 * numpy.dot(output_error * O_output * (1 - O_output), O_hidden.T))
  W_input_hidden = W_input_hidden - (-0.1 * numpy.dot(hidden_error * O_hidden * (1 - O_hidden), I.T))

  if epoch % 100 == 0:
    print('Epoch:', epoch)
    total_error = numpy.sum(output_error ** 2)
    print('Error:', '{0:.10f}'.format(total_error))

print('---Training Fininshed---\n')

Epoch: 0
Error: 0.1016448219
Epoch: 100
Error: 0.0287427015
Epoch: 200
Error: 0.0081838235
Epoch: 300
Error: 0.0023825505
Epoch: 400
Error: 0.0007263831
Epoch: 500
Error: 0.0002367784
Epoch: 600
Error: 0.0000825510
Epoch: 700
Error: 0.0000303607
---Training Fininshed---



In [ ]:
# Forward Pass
X_hidden = numpy.dot(W_input_hidden, I)
O_hidden = sigmoid_function(X_hidden)
X_output = numpy.dot(W_hidden_output, O_hidden)
O_output = sigmoid_function(X_output)
print('Output After Training:\n', O_output)
print('\nTarget:\n', target, '\n')

Output After Training:
 [[0.60127786]
 [0.79691272]
 [0.5006452 ]]

Target:
 [[0.6]
 [0.8]
 [0.5]] 



In [ ]:
print('\nNew Weight Matrixes')
print(W_input_hidden.shape)
print(W_input_hidden)
print('-------')
print(W_hidden_output.shape)
print(W_hidden_output)


New Weight Matrixes
(3, 3)
[[ 0.81474342  0.29052705  0.32421638]
 [ 0.40407065  0.82267452  0.38139613]
 [-0.49263378  0.4341518   0.07321442]]
-------
(3, 3)
[[-0.00712505  0.43671401  0.28720227]
 [ 0.91358922  0.77108557  0.4126951 ]
 [ 0.16012332 -0.44541396  0.45119395]]
