# ***Part 1***

## Forward Propagation

In [30]:
import numpy

In [31]:
in_arr = numpy.asarray([[0.9, 0.1, 0.8]]).T

array for inputs

In [32]:
weight1 = numpy.asarray([[0.9, 0.3, 0.4], [0.2, 0.8, 0.2], [0.1, 0.5, 0.6]])

array for weights in input_hidden

In [33]:
weight2 = numpy.asarray([[0.3, 0.7, 0.5], [0.6, 0.5, 0.2], [0.8, 0.1, 0.9]])

array for weights in hidden_output

In [34]:
import scipy.special
sigmoid_function = lambda x: scipy.special.expit(x)

dot1 = numpy.dot(weight1, in_arr)
sig1 = sigmoid_function(dot1)

dot2 = numpy.dot(weight2, sig1)
sig2 = sigmoid_function(dot2)

dot production and sigmoid function in input_hidden and hidden_output

In [35]:
output = sig2
print(output.shape)
print(output)

(3, 1)
[[0.72630335]
 [0.70859807]
 [0.77809706]]


show the output

## Backward Propagation

In [13]:
target = numpy.asarray([[0.6, 0.8, 0.5]]).T

set the target

In [15]:
error2 = target - output
error1 = numpy.dot(weight2.T, error2)

compute the error

In [16]:
weight1 = weight1 - (-0.01 * numpy.dot(error1 * sig1 * (1 - sig1), in_arr.T))
weight2 = weight2 - (-0.01 * numpy.dot(error2 * sig2 * (1 - sig2), sig1.T))

modify the weights

In [19]:
print('new weight1')
print(weight1.shape)
print(weight1)
print('')
print('new weight2')
print(weight2.shape)
print(weight2)

new weight1
(3, 3)
[[0.89966389 0.29996265 0.39970124]
 [0.19984812 0.79998312 0.199865  ]
 [0.09939584 0.49993287 0.59946297]]

new weight2
(3, 3)
[[0.29980885 0.69984848 0.49983675]
 [0.60014369 0.5001139  0.20012272]
 [0.79963443 0.09971023 0.89968779]]


show the new weights

## Train & Test

Train the neural network using the above code

In [48]:
import numpy
import scipy.special

sigmoid_function = lambda x: scipy.special.expit(x)

n_of_epochs = 1000

in_arr = numpy.asarray([[0.9, 0.1, 0.8]]).T
target = numpy.asarray([[0.6, 0.8, 0.5]]).T

weight1 = numpy.asarray([[0.9, 0.3, 0.4], [0.2, 0.8, 0.2], [0.1, 0.5, 0.6]])
weight2 = numpy.asarray([[0.3, 0.7, 0.5], [0.6, 0.5, 0.2], [0.8, 0.1, 0.9]])

for epoch in range(n_of_epochs):
  dot1 = numpy.dot(weight1, in_arr)
  sig1 = sigmoid_function(dot1)
  dot2 = numpy.dot(weight2, sig1)
  sig2 = sigmoid_function(dot2)

  error2 = target - sig2
  error1 = numpy.dot(weight2.T, error2)
  weight1 = weight1 - (-0.08 * numpy.dot(error1 * sig1 * (1 - sig1), in_arr.T))
  weight2 = weight2 - (-0.08 * numpy.dot(error2 * sig2 * (1 - sig2), sig1.T))

  if epoch % 100 == 0:
    print('Epoch:', epoch)
    total_error = numpy.sum(error2 ** 2)
    print('Error:', '{0:.10f}'.format(total_error))



Epoch: 0
Error: 0.1016448219
Epoch: 100
Error: 0.0370836347
Epoch: 200
Error: 0.0135081277
Epoch: 300
Error: 0.0049840413
Epoch: 400
Error: 0.0018730002
Epoch: 500
Error: 0.0007276854
Epoch: 600
Error: 0.0002951966
Epoch: 700
Error: 0.0001251684
Epoch: 800
Error: 0.0000551555
Epoch: 900
Error: 0.0000250391


Test

In [51]:
dot1 = numpy.dot(weight1, in_arr)
sig1 = sigmoid_function(dot1)
dot2 = numpy.dot(weight2, sig1)
sig2 = sigmoid_function(dot2)

output = sig2

print('Target')
print(target)
print('')
print('Output')
print(output)

Target
[[0.6]
 [0.8]
 [0.5]]

Output
[[0.60127967]
 [0.79690893]
 [0.50064746]]


# ***Part 2***

## Experiment with different weights, inputs, and targets (1)

In [63]:
import numpy
import scipy.special

sigmoid_function = lambda x: scipy.special.expit(x)

n_of_epochs = 1000

in_arr = numpy.asarray([[1.5, 1.3, 0.3]]).T
target = numpy.asarray([[0.2, 0.8, 1.8]]).T

weight1 = numpy.asarray([[0.3, 0.5, 0.1], [0.9, 0.5, 0.4], [0.6, 0.2, 0.9]])
weight2 = numpy.asarray([[0.7, 0.4, 0.3], [0.6, 0.3, 0.9], [0.4, 0.5, 0.1]])

for epoch in range(n_of_epochs):
  dot1 = numpy.dot(weight1, in_arr)
  sig1 = sigmoid_function(dot1)
  dot2 = numpy.dot(weight2, sig1)
  sig2 = sigmoid_function(dot2)

  error2 = target - sig2
  error1 = numpy.dot(weight2.T, error2)
  weight1 = weight1 - (-0.08 * numpy.dot(error1 * sig1 * (1 - sig1), in_arr.T))
  weight2 = weight2 - (-0.08 * numpy.dot(error2 * sig2 * (1 - sig2), sig1.T))

  if epoch % 100 == 0:
    print('Epoch:', epoch)
    total_error = numpy.sum(error2 ** 2)
    print('Error:', '{0:.10f}'.format(total_error))

Epoch: 0
Error: 1.5269917730
Epoch: 100
Error: 0.7648786276
Epoch: 200
Error: 0.6862587288
Epoch: 300
Error: 0.6683832534
Epoch: 400
Error: 0.6607076964
Epoch: 500
Error: 0.6564089555
Epoch: 600
Error: 0.6536355364
Epoch: 700
Error: 0.6516835488
Epoch: 800
Error: 0.6502282917
Epoch: 900
Error: 0.6490986837


## Experiment with different weights, inputs, and targets (2)

In [61]:
import numpy
import scipy.special

sigmoid_function = lambda x: scipy.special.expit(x)

n_of_epochs = 1000

in_arr = numpy.asarray([[0.8, 0.2, 0.7]]).T
target = numpy.asarray([[0.5, 0.9, 0.4]]).T

weight1 = numpy.asarray([[0.3, 0.3, 0.5], [0.6, 0.7, 0.2], [0.7, 0.5, 0.4]])
weight2 = numpy.asarray([[0.8, 0.7, 0.3], [0.1, 0.5, 0.1], [0.2, 0.1, 0.8]])

for epoch in range(n_of_epochs):
  dot1 = numpy.dot(weight1, in_arr)
  sig1 = sigmoid_function(dot1)
  dot2 = numpy.dot(weight2, sig1)
  sig2 = sigmoid_function(dot2)

  error2 = target - sig2
  error1 = numpy.dot(weight2.T, error2)
  weight1 = weight1 - (-0.08 * numpy.dot(error1 * sig1 * (1 - sig1), in_arr.T))
  weight2 = weight2 - (-0.08 * numpy.dot(error2 * sig2 * (1 - sig2), sig1.T))

  if epoch % 100 == 0:
    print('Epoch:', epoch)
    total_error = numpy.sum(error2 ** 2)
    print('Error:', '{0:.10f}'.format(total_error))

Epoch: 0
Error: 0.2347246953
Epoch: 100
Error: 0.0821123576
Epoch: 200
Error: 0.0295624975
Epoch: 300
Error: 0.0108253697
Epoch: 400
Error: 0.0044308152
Epoch: 500
Error: 0.0021357870
Epoch: 600
Error: 0.0011786132
Epoch: 700
Error: 0.0007061883
Epoch: 800
Error: 0.0004428480
Epoch: 900
Error: 0.0002852677


## Summary of what i have learned

I already had theoretical knowledge of the neural network training process, but I didn't know about the actual implementation. This task allows me to understand how to actually implement the forward propagation, backward propagation process to train neural networks, and write the code myself. Experiments with different values for the same code also taught me the importance of setting the right values, such as weights and target values, etc.

저는 신경망 훈련 과정에 대한 이론적 지식은 이미 가지고 있었지만, 실제 구현에 대해서는 알지 못했습니다. 이 과제를 통해  신경망을 훈련시키기 위한 forward propagation, backward propagation 과정을 실제로 코드로 어떻게 구현 하는지를 이해하고 직접 작성할 수 있게 되었습니다. 또한 동일한 코드에 대해 다른 값을 사용한 실험을 통해 가중치, target values 와 같은 값들을 알맞게 설정하는 것의 중요성을 배웠습니다.